discourse_rss_onebox:
  rss_onebox_enabled:
    default: false
  rss_onebox_categories:
    type: category_list
    default: ""
    client: false
  rss_onebox_enhanced:
    default: false
    client: false
  rss_onebox_youtube_descriptions:
    default: false
    client: false
  rss_onebox_blog_title_format:
    default: "%{title}"
    client: false
  rss_onebox_youtube_title_format:
    default: "%{title}"
    client: false
